/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gwoart;

import gwoart.Gwoart;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//        Gwoart gwoart = new Gwoart();
//        gwoart.sort();
    }
}
